### ISSUE TITLE
Canva Whatsapp link is boken

### ISSUE THREAD

**Issue by parlortrickss** [Welding-Torch/installc#4]
This link on the readme is broken

https://github.com/Welding-Torch/Install-C-readme/assets/46340124/68711e5d-946f-4507-8af6-5fe9e80f6298

**Comment by Welding-Torch** [comment]
Oh, I didn't realise at all! The image was rendering for me on my personal GitHub account, but turns out, it isn't visible generally. I've fixed the broken link now. Thanks for letting me know!
